### ISSUE TITLE
logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [Voyager-One/crypto-bot#2]
Hi, I want to design a new logo for the project completely free...

**Comment by cyphernull** [comment]
hey, what do you mean? you want to add a new logo for this project? you're quite welcome to do so : )
you can just fork this and set up a new branch : )

**Comment by Arslanshn** [comment]
Hi. Ok i'll start tomorrow.

**Comment by Arslanshn** [comment]
hi New logo link
https://drive.google.com/drive/folders/1jGq38nkQ_E-_8SK5Zukzs-LRQlM1N2hU?usp=sharing
I hope you liked it :)

**Comment by Arslanshn** [comment]
I apologize that the logo was also a problem and I am sending this evening ..

**Comment by Arslanshn** [comment]
I apologize that the logo was also a problem and I am sending this evening ..
https://drive.google.com/drive/folders/1jGq38nkQ_E-_8SK5Zukzs-LRQlM1N2hU?usp=sharing

**Comment by Arslanshn** [comment]
https://drive.google.com/drive/mobile/folders/1jGq38nkQ_E-_8SK5Zukzs-LRQlM1N2hU?usp=sharing

**Comment by Arslanshn** [comment]
Hi logoyu Did you like it please give an answer

**Comment by cyphernull** [comment]
it's a nice job. I appreciate that. I'm going to add it to the repo after my mid term☺️

**Comment by Arslanshn** [comment]
Today or tomorrow? İm waiting)

**Comment by cyphernull** [comment]
Hey @Arslanshn I've just added your contribution to the readme file. I will push changes to electron after a while. 

If you want to modify you can fork this repo and set on a new branch and then set a pull request so I can merge your branch. It's better for you to decide the icon display.

**Comment by Arslanshn** [comment]
Logoy'u beğendiğin için teşekkürler. Good evening☺️

**Comment by Arslanshn** [comment]
Thank you for liking Logoy
